POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTI0Mjc3NjksImVtYWlsIjoiMTIzNDU2N0BtYWlsLnV6Iiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY5MjUxNDE2OSwiaXNzIjoia3VudXogdGVzdCBwb3J0YWxpIn0.fPIJ9nUKyDM6IZHjFvM961XwduVg2BLiKcxvJEV7q1pidJZzOfL8QVc6RyKN0iw7j4vA0vGnEW1Y060XBwy1Nw

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="image3.webp"

< C:\Users\Nodirbek\Pictures\Saved Pictures\image3.webp

### get by id
GET http://localhost:8080/api/v1/attach/open/get/4f9d75dd-68f3-42e3-824a-3a8b375416c1

### delete
DELETE http://localhost:8080/api/v1/attach/admin/delete?id=97bbd144-353b-4ad5-bfbf-549ba7e1f1e0
